name: Build and Test Mega City Cab Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Container with NetBeans
      uses: addnab/docker-run-action@v3
      with:
        image: your-docker-image-with-netbeans
        options: -v ${{ github.workspace }}:/workspace
        run: |
          cd /workspace
          ant -f build.xml -Dj2ee.server.home=/

