name: Build and Test Mega City Cab Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11 (Adoptium/Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Apache Ant
      run: sudo apt-get install ant

    - name: Build Project with Ant
      run: ant -f build.xml

    - name: Run Tests
      run: ant -f build.xml test
