name: Check Controller Availability for Mega City Cab Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-components:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Check if Required Controller Classes Exist
      run: |
        # Define the directory where controllers are located
        CONTROLLER_DIR="./src/java/controller"
        
        # Define the required controllers
        REQUIRED_CONTROLLERS=("BookingController.java" "CancelBookingController.java" "LoginController.java")
        
        # Check if each required controller file exists
        for controller in "${REQUIRED_CONTROLLERS[@]}"; do
          if [ -f "$CONTROLLER_DIR/$controller" ]; then
            echo "$controller is present."
          else
            echo "$controller is missing!"
            exit 1
          fi
        done

        # Optionally, check if the build.xml file is present
        if [ -f "build.xml" ]; then
          echo "build.xml found."
        else
          echo "build.xml not found."
          exit 1
        fi
