name: Java Web App Deployment with Terraform

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '23.0.2'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 'latest'
    
    - name: Run tests (if necessary)
      run: mvn test  # Or your preferred testing command (e.g., gradle test)
    
    - name: Terraform Initialization
      run: terraform init
    
    - name: Apply Terraform
      run: terraform apply -auto-approve
    
    - name: Deploy Web Application
      run: |
        curl -u ${{ secrets.DEPLOY_USERNAME }}:${{ secrets.DEPLOY_PASSWORD }} -X POST http://220.247.246.76:8080/deploy  # Replace this with your actual deploy command
